# Site settings
name: Kelly Atkinson
title: Kelly Atkinson | Archery CV
description: Olympic recurve archer representing New Zealand in World Archery and IFAA field events
url: https://archery.ai
baseurl: ''
email: kelly@archery.ai
cover: https://archery.ai/img/og.png
logo: https://archery.ai/img/emojis/technologist.png
social:
  - title: email
    url: mailto:kelly@archery.ai
  - title: instagram
    url: https://instagram.com/archersci
  - title: github
    url: https://github.com/kellyatkinson

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
